// Code generated by protoc-gen-go.
// source: stream.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	stream.proto

It has these top-level messages:
	Request
	EventType
	Payload
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Events     []*EventType `protobuf:"bytes,1,rep,name=Events" json:"Events,omitempty"`
	ForceClose bool         `protobuf:"varint,2,opt,name=forceClose" json:"forceClose,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetEvents() []*EventType {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Request) GetForceClose() bool {
	if m != nil {
		return m.ForceClose
	}
	return false
}

type EventType struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *EventType) Reset()                    { *m = EventType{} }
func (m *EventType) String() string            { return proto1.CompactTextString(m) }
func (*EventType) ProtoMessage()               {}
func (*EventType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Payload struct {
	EventType *EventType `protobuf:"bytes,1,opt,name=eventType" json:"eventType,omitempty"`
	Data      string     `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto1.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Payload) GetEventType() *EventType {
	if m != nil {
		return m.EventType
	}
	return nil
}

func (m *Payload) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto1.RegisterType((*Request)(nil), "proto.Request")
	proto1.RegisterType((*EventType)(nil), "proto.EventType")
	proto1.RegisterType((*Payload)(nil), "proto.Payload")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StreamService service

type StreamServiceClient interface {
	Events(ctx context.Context, opts ...grpc.CallOption) (StreamService_EventsClient, error)
}

type streamServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamServiceClient(cc *grpc.ClientConn) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) Events(ctx context.Context, opts ...grpc.CallOption) (StreamService_EventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StreamService_serviceDesc.Streams[0], c.cc, "/proto.StreamService/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceEventsClient{stream}
	return x, nil
}

type StreamService_EventsClient interface {
	Send(*Request) error
	Recv() (*Payload, error)
	grpc.ClientStream
}

type streamServiceEventsClient struct {
	grpc.ClientStream
}

func (x *streamServiceEventsClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceEventsClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for StreamService service

type StreamServiceServer interface {
	Events(StreamService_EventsServer) error
}

func RegisterStreamServiceServer(s *grpc.Server, srv StreamServiceServer) {
	s.RegisterService(&_StreamService_serviceDesc, srv)
}

func _StreamService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Events(&streamServiceEventsServer{stream})
}

type StreamService_EventsServer interface {
	Send(*Payload) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type streamServiceEventsServer struct {
	grpc.ServerStream
}

func (x *streamServiceEventsServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceEventsServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _StreamService_Events_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}

func init() { proto1.RegisterFile("stream.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x4d, 0xd5, 0xad, 0x3b, 0xfe, 0xa1, 0xcc, 0x69, 0x11, 0xd4, 0x65, 0x4f, 0x39, 0x05,
	0xa9, 0x0f, 0x20, 0x55, 0xbc, 0x59, 0x58, 0x12, 0x5f, 0x20, 0xb6, 0x53, 0x14, 0xb6, 0x4d, 0x4c,
	0xe2, 0xc2, 0xbe, 0x8e, 0x4f, 0x2a, 0x8e, 0x59, 0xf5, 0xe0, 0x29, 0x93, 0x99, 0xdf, 0xf7, 0x7d,
	0x7c, 0x70, 0x12, 0x53, 0x20, 0xbb, 0x55, 0x3e, 0xb8, 0xe4, 0xf0, 0x90, 0x9f, 0xc6, 0xc0, 0x54,
	0xd3, 0xdb, 0x3b, 0xc5, 0x84, 0x12, 0x8a, 0x87, 0x9e, 0x76, 0x29, 0x56, 0xa2, 0xde, 0x97, 0xc7,
	0xf3, 0xd9, 0x37, 0xa9, 0x78, 0xf9, 0x34, 0x78, 0xd2, 0xf9, 0x8e, 0x97, 0x00, 0x1b, 0x17, 0x56,
	0x74, 0xdf, 0xb9, 0x48, 0xd5, 0xa4, 0x16, 0xf2, 0x48, 0xff, 0xd9, 0x34, 0x57, 0x50, 0xfe, 0x88,
	0x10, 0xe1, 0x20, 0x0d, 0x9e, 0x2a, 0x51, 0x0b, 0x59, 0x6a, 0x9e, 0x9b, 0x25, 0x4c, 0x5b, 0x3b,
	0x74, 0xce, 0xae, 0x51, 0x41, 0x49, 0x23, 0xcb, 0xcc, 0x7f, 0xc1, 0xbf, 0xc8, 0x97, 0xdd, 0xda,
	0x26, 0xcb, 0xa9, 0xa5, 0xe6, 0x79, 0x7e, 0x0b, 0xa7, 0x86, 0xbb, 0x19, 0x0a, 0xfd, 0xeb, 0x8a,
	0x50, 0x8d, 0x55, 0xf0, 0x2c, 0x7b, 0xe5, 0x92, 0xe7, 0xe3, 0x3f, 0xc7, 0x37, 0x7b, 0x52, 0x5c,
	0x8b, 0xbb, 0x0b, 0x98, 0x39, 0x4f, 0xbb, 0x4d, 0xa0, 0xf8, 0xa2, 0x7c, 0x67, 0xe3, 0xd6, 0xb6,
	0xe2, 0x63, 0x52, 0xb4, 0x8f, 0x0b, 0xb3, 0x5c, 0x3c, 0x17, 0xac, 0xb9, 0xf9, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0xea, 0xee, 0xc6, 0x42, 0x01, 0x00, 0x00,
}
